[tool.flake8]
max-line-length = 120

[tool.autopep8]
max_line_length = 128
in-place = true
recursive = true

[tool.isort]
line_length = 120
import_heading_stdlib = "### Built-in deps"
import_heading_thirdparty = "### Third-party deps"
import_heading_firstparty = "### Local deps"
color_output = true
verbose = false
split_on_trailing_comma = true

[tool.pylint]
max-line-length=120

[tool.mypy]
files = ["<package name>/"]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true

[tool.codespell]
skip = '*.po,*.ts,*.txt,*.json'
count = '2'
quiet-level = 3

[tool.docformatter]
recursive = true
wrap-summaries = 120
wrap-descriptions = 128
in-place = true
blank = true
